#开发环境
server: 
  port: 18080

#数据源
dataSource: 
  bySearch: 
    testWhileIdle: true
    validationQuery: SELECT 1
    timeBetweenEvictionRunsMillis: 3600000
    
spring: 
  datasource: 
    url: jdbc:mysql://172.30.55.108:3306/likeblog
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

upload: 
  path: D:/springUpload/