
#生产环境
server: 
  port: 18080

#数据源
dataSource: 
  bySearch: 
    testWhileIdle: true
    validationQuery: SELECT 1
    timeBetweenEvictionRunsMillis: 3600000

spring: 
  datasource: 
    url: jdbc:mysql://rm-uf6tv42kdrjl8z5y7o.mysql.rds.aliyuncs.com:3306/likeblog
    username: root
    password: root1234@
    driver-class-name: com.mysql.jdbc.Driver

upload: 
  path: /likeblog/nginx/html/static/likeImg/